jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: jaffle-postgress.postgres.database.azure.com
      user: jessepostgres@jaffle-postgress
      password: l3x2NJyoaGCs
      port: 5432
      dbname: postgres
      schema: default
      threads: 1
      keepalives_idle: 60 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      sslmode: disable
